FROM php:7.1-apache

RUN a2enmod rewrite

COPY ./ /var/www/html/
COPY ./ /var/www/


ENV APP_ENV=local \
    APP_DEBUG=false \
    APP_KEY=key \
    APP_TIMEZONE=UTC \

CMD sed -i "s/80/$PORT/g" /etc/apache2/sites-available/000-default.conf /etc/apache2/ports.conf \ 
    && docker-php-entrypoint apache2-foreground